sudo: false
language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
install:
  - composer self-update
  - composer update
script:
  - ./vendor/bin/phpunit
  - find ./src -name "*.php" -print0 | xargs -0 -n1 -P256 php -l
  - ./vendor/bin/phpcs --standard=PSR2 ./src
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  fast_finish: true
